export default[]=[
{
id:"1",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"engineering",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
{
id:"2",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"medical",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
{
id:"3",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"business",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
{
id:"4",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"business",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
{
id:"5",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"business",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
{
id:"6",
name:"KDK COLLEGE OF ENGINEERING",
ranking:"500",
package:"4LPA",
cutoff:"80+",
m_course:"business",
o_course:["MTECH","MBA","MCA"],
address:"KDK College Rd, Opposite Telephone Exchange, Nandanvan, Nagpur, Maharashtra 440009",
website:"https://www.kdkce.edu.in/",
fees:"₹1,07,000",
logo:"./pic/logo.png",
photo:["./pic/pic1.jpg","./pic/pic2.jpg","./pic/pic3.jpg","./pic/pic4.jpg"],
v_photo:"./pic/v_photo.jpg"
},
]
